production: 
  encoding: unicode
  adapter: postgresql
  username: dekkstszmk
  port: 5432
  host: ec2-184-72-250-165.compute-1.amazonaws.com
  database: dekkstszmk
  password: f5lxx1zz5pnorynqglhzmsp34
